# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b190682e3e59da59a580e546f86b84f1d03ec2a9ad5e6b8efb48fec8958bf5a5eb5f6b5f115b28442a5dcd731608ae8bcc35c0ff21f80546a50521ed457c12d0

test:
  secret_key_base: 8594fe1f41e36a446e044779726ea5fd8a8e95a3f53e9fbf94f29df56e2c9ae2c637e0ee2bb7e644b1b8ae1547cfa6d6760de2d4a5f0fb0795bd76aa1502fcd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
